### ISSUE TITLE
Deploy on netlify

### ISSUE THREAD

**Issue by felixerdy** [codeformuenster/busradar#2]
Deploy to netlify, please.

Build commands:
```
yarn
yarn build
```
And serve the `build` folder.

Please add a mapbox access token environment variable named `MapboxAccessToken`

**Comment by ubergesundheit** [comment]
Live on https://busradar.codeformuenster.org/ and https://www.busradar.codeformuenster.org/

**Comment by ubergesundheit** [comment]
`MapboxAccessToken` is set, but it seems the build uses the acces token already present in the code. I think the variable declaration in code needs to be removed.
